version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: kcd-scripts
    versions:
    - 7.5.5
    - 7.6.0
    - 7.7.0
    - 8.0.2
    - 8.1.0
    - 8.1.1
    - 8.2.1
    - 8.3.0
    - 9.0.0
    - 9.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
